In [1]:
# Import Libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_absolute_error, median_absolute_error, r2_score
from sqlalchemy import create_engine

from config import db_password

In [2]:
# Connect to Database
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/IMDB_Movie_Data"

engine = create_engine(db_string).connect()

In [3]:
# Load data from Database into pandas DataFrame
X = pd.read_sql("""select animation, western, mystery, horror, romance,
    tv_movie, war, action, clean_kaggle.foreign, music,
    thriller, documentary, science_fiction, adventure, drama, 
    comedy, family, fantasy, history, crime, 
    has_collection
    from clean_kaggle where runtime is not null""", con=engine)
y = pd.read_sql("select revenue from clean_kaggle where runtime is not null", con=engine)



In [4]:
# Features
X.shape

(2991, 21)

In [5]:
# Predictor Variable
y.shape

(2991, 1)

In [6]:
# Split data features/targets into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

## Linear Regression Model

In [7]:
# Initiate the model
model = LinearRegression().fit(X_train, y_train)

# Start Prediction
y_pred = model.predict(X_test)

In [8]:
# Check model scores
# mean absolute error
mae = round(mean_absolute_error(y_test, y_pred),2)
# median absolute error
medae = round(median_absolute_error(y_test, y_pred),2)
# r2 score
r2score = round(r2_score(y_test, y_pred),2)

print(f"Mean Absolute Error: {mae}")
print(f"Median Absolute Error: {medae}")
print(f"r-squared Score: {r2score}")

# Score with cross validation
print(cross_val_score(model, X, y, cv=3))

Mean Absolute Error: 63176576.43
Median Absolute Error: 34185785.45
r-squared Score: 0.09
[0.18237201 0.18709819 0.20160767]


## Random Forest Regression

In [9]:
# Initiate model 
model = RandomForestRegressor(n_estimators=100).fit(X_train,y_train)

# Start Prediction
y_pred = model.predict(X_test)

/var/folders/08/cz61q4zj7yv62jvgdzxb94q80000gn/T/ipykernel_94894/1584661389.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model = RandomForestRegressor(n_estimators=100).fit(X_train,y_train)


In [10]:
# Check model scores
# mean absolute error
mae = round(mean_absolute_error(y_test, y_pred),2)
# median absolute error
medae = round(median_absolute_error(y_test, y_pred),2)
# r2 score
r2score = round(r2_score(y_test, y_pred),2)

print(f"Mean Absolute Error: {mae}")
print(f"Median Absolute Error: {medae}")
print(f"r-squared Score: {r2score}")

# Score with cross validation
print(cross_val_score(model, X, y, cv=3))

Mean Absolute Error: 63292638.29
Median Absolute Error: 34266543.09
r-squared Score: -0.16


/Users/machadolluis/miniforge3/envs/mlenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/machadolluis/miniforge3/envs/mlenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[0.15281958 0.10701937 0.23149067]


/Users/machadolluis/miniforge3/envs/mlenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


## Final Model with Validation

After comparing each model's scores, we choose one and use K-Folds cross-validation for the final prediction 

In [11]:
from sklearn.model_selection import KFold

# Initialize the model
final_model = RandomForestRegressor(n_estimators=100, random_state=16).fit(X_train, y_train)
# Use K-Folds cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=91)
for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    final_model.fit(X_train, y_train)
    y_pred = final_model.predict(X_test)

/var/folders/08/cz61q4zj7yv62jvgdzxb94q80000gn/T/ipykernel_94894/1174332434.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  final_model = RandomForestRegressor(n_estimators=100, random_state=16).fit(X_train, y_train)
/var/folders/08/cz61q4zj7yv62jvgdzxb94q80000gn/T/ipykernel_94894/1174332434.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  final_model.fit(X_train, y_train)
/var/folders/08/cz61q4zj7yv62jvgdzxb94q80000gn/T/ipykernel_94894/1174332434.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  final_model.fit(X_train, y_train)
/var/folders/08/cz61q4zj7yv62jvgdzxb94q80000gn/T/ipykernel_94894/1174332434.py:10: DataConversionWarning: A column-vecto

In [12]:
# Check final scores
# mean absolute error
mae = round(mean_absolute_error(y_test, y_pred),2)
# median absolute error
medae = round(median_absolute_error(y_test, y_pred),2)
# r2 score
r2score = round(r2_score(y_test, y_pred),2)

print(f"Mean Absolute Error: {mae}")
print(f"Median Absolute Error: {medae}")
print(f"r-squared Score: {r2score}")

# Score with cross validation
print(cross_val_score(final_model, X, y, cv=3))

/Users/machadolluis/miniforge3/envs/mlenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


Mean Absolute Error: 71332648.12
Median Absolute Error: 30033029.44
r-squared Score: 0.23


/Users/machadolluis/miniforge3/envs/mlenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/machadolluis/miniforge3/envs/mlenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


[0.16456787 0.09342974 0.22725309]
